[profile.alpha]
features = ["simple"]

[profile.beta]
features = ["dense", "restart"]

[profile.gamma]
features = ["restart", "ordered"]

[profile.delta]
features = ["accounting"]

[profile.epsilon]
features = ["roll", "restart"]

[profile.zeta]
features = ["dense", "restart", "roll", "ordered"]
