pub mod io;
pub mod model;
pub mod report;
pub mod runner;

#[path = "../r0/a.rs"]
pub mod r0_a;
#[path = "../r1/b.rs"]
pub mod r1_b;
#[path = "../r2/c.rs"]
pub mod r2_c;
#[path = "../r3/d.rs"]
pub mod r3_d;
#[path = "../r4/e.rs"]
pub mod r4_e;
#[path = "../r5/f.rs"]
pub mod r5_f;
#[path = "../r6/g.rs"]
pub mod r6_g;
#[path = "../r7/h.rs"]
pub mod r7_h;
#[path = "../r8/i.rs"]
pub mod r8_i;
